update:
  enable: true # false = the sidebar only is updated on player join
  seconds: 5

title: "&e&lYou server" # Don't support placeholder in title for HEAVY reduce cpu usage
lines:
  - "&bName: &f%qplayer_name%"
  - "&bPing: &f%qplayer_ping%ms"
  - ""
  - "&bQScoreboard v6.0:"
  - "  &fAdd new features"
  - "  &fCode cleanup"
  - "  &fRecode"

placeholder-api-support: true

# This are lightweight placeholders for don't download a extension in placeholderapi
#
# qplayer:
#    %qplayer_name% : player name
#    %qplayer_displayname% : custom playername
#    %qplayer_ping% : player ping
#
# qserver:
#    %qserver_online% : amount of player online

enable-custom-placeholders:
  qplayer: true
  qserver: false